"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$directory\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$c\
$cmake\
$golang\
$java\
$kotlin\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$zig\
$buf\
$nix_shell\
$sudo\
$time\
$status\
$container\
$shell\
$character
"""

[username]
show_always = true
style_user = 'red bold'
format = '[ J]($style)'
disabled = false

[directory]
# style = "fg:color_fg0 bg:color_yellow"
style = "italic blue"
format = "[ $path ]($style)"
truncation_length = 3

[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[ 󰅐 $time ](fg:color_fg0 bg:color_bg1)]($style)'

[rust]
version_format = "v${major}"
format = "[$symbol($version )]($style)"

[lua]
symbol = ' ' 
format = "[$symbol($version )]($style)"

[python]
symbol = ' '
format = "[$symbol($version )]($style)"
